# Generated by Django 4.2.5 on 2023-10-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentmode_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=20, unique=True)),
                ('paid_by', models.CharField(max_length=30)),
                ('trans_date', models.DateTimeField(verbose_name='Trancation Date')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmode')),
            ],
        ),
    ]
