# Generated by Django 4.2.5 on 2023-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
